<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>split.ai</groupId>
        <artifactId>split-service</artifactId>
        <version>0.0.1-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>split-service-core</artifactId>
    <packaging>jar</packaging>
    <name>Split Service Core</name>
    <description>Business logic services</description>

    <dependencies>
        <dependency>
            <groupId>split.ai</groupId>
            <artifactId>split-service-repository</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>io.split</groupId>
            <artifactId>split-engine-jvm</artifactId>
            <version>${split-engine.version}</version>
        </dependency>
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
            <version>${mapstruct.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>${commons-lang.version}</version>
        </dependency>

    </dependencies>
</project>
